import LegalPageLayout from '../components/LegalPageLayout';

export default function Privacy() {
  return (
    <LegalPageLayout title="Privacy Policy" lastUpdated="October 2026">
      <h2 className="text-xl font-bold text-eclipse-bright mt-8 mb-4">1. Introduction</h2>
      <p>
        Welcome to EclipseID. We are committed to protecting your privacy and ensuring you have total control over your personal data. Because EclipseID is built on the Midnight Network using Zero-Knowledge (ZK) cryptography, our core architecture is designed to minimize the data we store and maximize your privacy.
      </p>

      <h2 className="text-xl font-bold text-eclipse-bright mt-8 mb-4">2. Data We Do NOT Collect</h2>
      <p>
        EclipseID does <strong>not</strong> store your Personally Identifiable Information (PII) in plain text on any public ledger. Your raw KYC data (such as government IDs, names, or addresses) remains encrypted off-chain or on your local device. We only process mathematical proofs (ZK-SNARKs) that verify your compliance status.
      </p>

      <h2 className="text-xl font-bold text-eclipse-bright mt-8 mb-4">3. Data We Collect</h2>
      <p>
        When you interact with the EclipseID Protocol, we may collect:
      </p>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>On-Chain Data:</strong> Your public Midnight Network wallet address and transaction hashes related to proof submissions.</li>
        <li><strong>Application Data:</strong> Basic telemetry, error logs, and session data required to maintain the stability of the frontend interface.</li>
      </ul>

      <h2 className="text-xl font-bold text-eclipse-bright mt-8 mb-4">4. How We Use Your Data</h2>
      <p>
        The ZK proofs generated by your wallet are submitted to the Midnight Network to verify your identity status to third-party dApps (like the Darkpool) without revealing the underlying data. Telemetry data is used strictly for debugging and improving the user experience of the EclipseID web interface.
      </p>

      <h2 className="text-xl font-bold text-eclipse-bright mt-8 mb-4">5. Third-Party Sharing</h2>
      <p>
        We do not sell, rent, or trade any of your data. Third-party dApps only receive a cryptographic boolean (True/False) confirming your compliance, preventing them from profiling you or leaking your personal information.
      </p>

      <h2 className="text-xl font-bold text-eclipse-bright mt-8 mb-4">6. Contact Us</h2>
      <p>
        For any privacy-related questions or concerns regarding the EclipseID Protocol, please contact us at <a href="mailto:privacy@eclipse-id.com" className="text-eclipse-cyan hover:underline">privacy@eclipse-id.com</a>.
      </p>
    </LegalPageLayout>
  );
}
